### PR TITLE
Optimize image assets

### PR DESCRIPTION
**Pull request by m-byondlabs**
1. Reduce the dimension to 128px for all the category and subcategory image assets
2. Run image compression to reduce the size further

This has helped to reduce the assets size to go down from 150MB to 2.4MB

### CODE REVIEW

**Comment by navdeep710** [comment]
@Punit-Vajpeyi can you help in review or commenting

**Comment by Punit-Vajpeyi** [comment]
@m-byondlabs Unfortunately, we are unable to merge it at this time. The reason for this decision is that we have recently made significant updates to our category and sub-category list. Additionally, we have transitioned to loading images from our CDN to improve performance and reliability.
Given these changes, the modifications proposed in your pull request are no longer compatible with the current structure of our codebase

**Comment by m-byondlabs** [comment]
@Punit-Vajpeyi Great to know about the CDN change, do you think it would make sense to delete these assets if they are not used anymore? The fact that these assets add 150MB to the final apk/bundlke size, deleting them will help reduce the app size significantly.

**Comment by Punit-Vajpeyi** [comment]
@m-byondlabs Yes correct. We have deleted the assets from the main branch.

**Pull request closed without merging**
